blog/urls.py
from django.urls import path
from . import views 
app_name='blog'

urlpatterns = [
    path('',  views.post_list, name='post_list'),
    path('<int:id>',  views.post_detail, name='post_detail'),
    path('about_us/',  views.about_us, name='about_us'),
    path('summernote/', include('django_summernote.urls')),
    


]

contact/urls.py
from django.urls import path
from . import views 
app_name='contact'
urlpatterns = [
    path('',  views.send_email, name='send_email'),
    path('success/',  views.send_success, name='send_success'),
   
]

home/urls.py
from django.urls import path
from . import views 
app_name='home'
urlpatterns = [
    path('',  views.home, name='home'),
   
]

meals/urls.py
from django.urls import path
from . import views 
app_name='meals'
urlpatterns = [
    path('',  views.meal_list),
    path('<slug:slug>',  views.meal_detail, name='meal_detail'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls', namespace='home')),
    path('meals/', include('meals.urls', namespace='meals')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('reservation/', include('reservation.urls', namespace='reservation')),
    path('admin/', admin.site.urls),

]
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import path
from . import views 
app_name='reservation'
urlpatterns = [
    path('',  views.reservation, name='reservation'),

]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
# Create your models here.
class Post(models.Model):

	title=models.CharField(default='', max_length=300)
	content=models.TextField(default='')
	author=models.ForeignKey(User, default='', on_delete=models.CASCADE)
	image=models.ImageField(upload_to='media/meals/')
	created=models.DateField(default=timezone.now)
	# tags=
	category=models.ForeignKey("Category", on_delete=models.SET_NULL, null=True)
	views=models.IntegerField(default=0)

	tags=TaggableManager(blank=True)

	def __str__(self):
		return self.title

class Category(models.Model):
	name=models.CharField(default='', max_length=300)
	def __str__(self):
		return self.name
class Comments(models.Model):
	 user=models.ForeignKey(User, on_delete=models.CASCADE)
	 post=models.ForeignKey(Post, on_delete=models.CASCADE)
	 content=models.TextField(default='')
	 created=models.DateTimeField(default=timezone.now)

home/models.py
from django.db import models

# Create your models here.

meals/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.
class Meals(models.Model):
	name=models.CharField(max_length=50)
	description=models.TextField(max_length=500)
	category=models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
	people=models.IntegerField()
	price=models.DecimalField(max_digits=5, decimal_places=2)
	preparation_time=models.IntegerField()
	image=models.ImageField(upload_to='meals/')
	slug=models.SlugField(blank=True, null=True)


	def save(self, *args, **kwargs):
		if not self.slug and self.name:
			self.slug=slugify(self.name)
		super(Meals, self).save(*args, **kwargs)

	class Meta:
		verbose_name='meal'
		verbose_name_plural='meals'


	def __str__(self):
		return self.name


class Category(models.Model):
	category_name=models.CharField(default='', max_length=200)

	def __str__(self):
		return self.category_name
	class Meta:
		verbose_name='category'
		verbose_name_plural='categories'

reservation/models.py
from django.db import models

# Create your models here.
class Reservation(models.Model):
	name=models.CharField(default='', max_length=100)
	email=models.EmailField(default='')
	phone=models.IntegerField()
	number_of_persons=models.IntegerField()
	Date=models.DateField()
	time=models.TimeField()


	# def __str__(self):
	# 	self.name

blog/forms.py
from django import forms
from .models import Comments
class CommentForm(forms.ModelForm):
	class Meta:
		model=Comments
		fields={'content'}

contact/forms.py
from django import forms

class ContactForm(forms.Form):
	subject=forms.CharField()
	from_email=forms.EmailField(required=True)
	message=forms.CharField(widget=forms.Textarea, required=True)

reservation/forms.py
from django import forms
from .models import Reservation

class ReservationForm(forms.ModelForm):
	class Meta:
		model=Reservation
		fields='__all__'

blog/views.py
from django.shortcuts import render
from .models import Post, Category, Comments
from .forms import CommentForm

# Create your views here.
def post_list(request):
	posts=Post.objects.all()
	category=Category.objects.all()
	context={'posts':posts, 'category':category}
	return render(request, 'Blog/post_list.html', context)

def post_detail(request, id):
	post_detail=Post.objects.get(id=id)
	category=Category.objects.all()
	comments=Comments.objects.filter(post=post_detail)
	comment_form=CommentForm()

	if request.method=="POST":
		comment_form=CommentForm(request.POST)
		if comment_form.is_valid():
			new_comment=comment_form.save(commit=False)
			new_comment.user=request.user
			new_comment.post=post_detail
			new_comment.save()

	else:
		comment_form=CommentForm()
	context={'post_detail':post_detail,
			'category':category,
			'comments':comments,
			'comment_form':comment_form
	}
	return render(request, 'Blog/post_detail.html', context)


def about_us(request):
	return render(request, "Blog/about.html", {})

contact/views.py
from django.shortcuts import render
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from .forms import ContactForm
from django.shortcuts import redirect


# Create your views here.
def send_email(request):
	if request.method=="POST":
		form=ContactForm(request.POST)
		if form.is_valid():
			subject=form.cleaned_data['subject']
			from_email=form.cleaned_data['from_email']
			message=form.cleaned_data['message']

			try:
				send_mail(subject, message, from_email, ['admin.ch@gmail.com'])
			except BadHeaderError:
				return HttpResponse('invalid header')
			return redirect('contact:send_success')

	else:
		form=ContactForm()

	context={'form':form}
	return render(request, 'contact/contact.html', context)

def send_success(request):
	return HttpResponse('Thanks, your email is submitted')

home/views.py
from django.shortcuts import render
from meals.models import Category, Meals
from blog.models import Post
# Create your views here.
def home(request):
	meal_list=Meals.objects.all()
	category=Category.objects.all()
	posts=Post.objects.all()
	context={"meal_list":meal_list,
	"category":category,
	'posts':posts}

	return render(request, 'home/index.html', context)

meals/views.py
from django.shortcuts import render
from .models import Meals, Category
# Create your views here.
def meal_list(request):
	meal_list=Meals.objects.all()
	category=Category.objects.all()
	context={'meal_list':meal_list, 'category':category}
	return render(request, 'Meals/list.html', context)

def meal_detail(request, slug):
	meal_detail=Meals.objects.get(slug=slug)
	context={'meal_detail':meal_detail}
	return render(request, 'Meals/detail.html', context)

reservation/views.py
from django.shortcuts import render
from .models import Reservation
from .forms import ReservationForm
# Create your views here.
def reservation(request):
	reserve_form=ReservationForm()
	if request.method=="POST":
		reserve_form=ReservationForm(request.POST)
		if reserve_form.is_valid():
			reserve_form.save()

	context={'reserve_form':reserve_form}
	return render(request, 'Reservation/reservation.html', context)

blog/templates/Blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}

      
      <div class="main-wrap">
        <div class="cover_1">
          <div class="img_bg" style="background-image: url({% static 'img/slider-1.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center justify-content-center">
                <div class="col-md-7 text-center" data-aos="fade-up">
                  <h2 class="heading mb-4">{{post_detail}}</h2>

                  <div class="post-info">
                    <div class="date-info">{{post_detail.created}}</div>
                    <div class="category-info"><span class="seperator">|</span>In <a href="#" data-title="View all posts in Lifestyle" title="View all posts in Lifestyle">{{post_detail.category}}</a></div>
                    <div class="author-info"><span class="seperator">|</span>By <a href="#">{{post_detail.author}}</a></div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

       <div class="section">
          <div class="container">
            
            <div class="row">

              <div class="col-md-8">
                <p>{{post_detail.content}}</p>

                

                <div class="tag-widget post-tag-container mb-5 mt-5">
                  <div class="tagcloud">
                    {% for tag in post_detail.tags.all %}
                    <a href="#" class="tag-cloud-link">{{tag.name}}</a>
                    {% endfor %}
                  </div>
                </div>


                <div class="pt-5 mt-5">
                  <h3 class="mb-5">6 Comments</h3>
                  <ul class="comment-list">
                    <li class="comment">
                      <div class="vcard bio">
                        <img src="{% static 'img/person_1.jpg' %}" alt="Image placeholder">
                      </div>
                      {% for comment in comments %}
                      <div class="comment-body">
                        <h3>{{comment.user}}</h3>
                        <div class="meta">{{comment.created}}</div>
                        <p>{{comment.content}}</p>
                        <p><a href="#" class="reply">Reply</a></p>
                      </div>
                      {% endfor %}
                    </li>
                  </ul>
                  <!-- END comment-list -->
                  
                  <div class="comment-form-wrap pt-5">
                    <h3 class="mb-5">Leave a comment</h3>
                    <form  method="POST" class="p-5 bg-light">
                      {% csrf_token %}
                      {% bootstrap_form comment_form %}

                     <!--  <div class="form-group">

                        <label for="name">Name *</label>
                        <input type="text" class="form-control" id="name">
                      </div>
                      <div class="form-group">
                        <label for="email">Email *</label>
                        <input type="email" class="form-control" id="email">
                      </div>
                      <div class="form-group">
                        <label for="website">Website</label>
                        <input type="url" class="form-control" id="website">
                      </div>

                      <div class="form-group">
                        <label for="message">Message</label>
                        <textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>
                      </div> -->
                      {% buttons %}
                      <div class="form-group">
                        <input type="submit" value="Post Comment" class="btn btn-primary">
                      </div>
                      {% endbuttons %}

                    </form>
                  </div>
                </div>

              </div> <!-- .col-md-8 -->
              <div class="col-md-4 sidebar">
                <div class="sidebar-box">
                  <form action="#" class="search-form">
                    <div class="form-group">
                      <span class="icon fa fa-search"></span>
                      <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                    </div>
                  </form>
                </div>
                <div class="sidebar-box">
                  <div class="categories">
                    <h3>Categories</h3>
                    {%for cat in category%}

                    <li><a href="#">{{cat }} </a></li>
                    {% endfor %}
                  </div>
                </div>
                <div class="sidebar-box">
                  <img src="img/person_1.jpg" alt="Image placeholder" class="img-fluid mb-4">
                  <h3>About The Author</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
                  <p><a href="#" class="btn btn-primary btn-sm">Read More</a></p>
                </div>

                
                <div class="sidebar-box">
                  <h3>Paragraph</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
                </div>
              </div>

            </div>

            
          </div>
        </div> <!-- .section -->
      


      </div> <!-- .main-wrap -->
      {% endblock %}

blog/templates/Blog/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

      
      
      <div class="main-wrap">
        <div class="cover_1">
          <div class="img_bg" style="background-image: url({% static 'img/slider-1.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-md-12" data-aos="fade-up">
                  <h2 class="heading">Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit ipsa sint amet aliquam velit minima tenetur quisquam beatae molestiae possimus dicta.</h2>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

         <div class="section">
          <div class="container">
            
            <div class="row mb-5">
             
              {%for post in posts %}
              <div class="col-md-4">
                <div class="media d-block media-bg-white mb-5" data-aos="fade-up"  data-aos-delay="400">
                  <figure>
                    <a href="{% url 'blog:post_detail' post.id %}" ><img src="{{post.image.url}}" alt="Image placeholder" class="img-fluid"></a>
                  </figure>
                  <div class="media-body">
                    <h3><a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a></h3>
                    <p class="post-meta"><span><span class="fa fa-calendar"></span> Date: {{post.created}}</span></p>
                    <p class="post-meta"><span><span class="fa fa-eye"></span> {{post.views}}</span></p>
                    <p class="mb-4">{{post.content}}</p>
                    <p><a href="#" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>
                  </div>
                </div> <!-- .media -->
              </div>
              {% endfor %}
              
              

            </div>

            <div class="row">
              <div class="col-md-12">
                <ul class="pagination custom-pagination">
                  <li class="page-item prev"><a class="page-link" href="#"><i class="fa fa-angle-left"></i></a></li>
                  <li class="page-item active"><a class="page-linkx href="#">1</a></li>
                  <li class="page-item"><a class="page-link" href="#">2</a></li>
                  <li class="page-item"><a class="page-link" href="#">3</a></li>
                  <li class="page-item next"><a class="page-link" href="#"><i class="fa fa-angle-right"></i></a></li>
                </ul>


              </div>
            </div>
          </div>
        </div> <!-- .section -->
      


      </div> <!-- .main-wrap -->
      

     {% endblock %}

meals/templates/Meals/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

      
      <div class="main-wrap">
        <div class="cover_1">
          <div class="img_bg" style="background-image: url({% static 'img/slider-1.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-md-12" data-aos="fade-up">
                  <h2 class="heading">Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit ipsa sint amet aliquam velit minima tenetur quisquam beatae molestiae possimus dicta.</h2>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->


        <div class="section">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-8" data-aos="fade-up">

                <h2 class="mb-5 text-center">Menu List with Price</h2>

                <ul class="nav site-tab-nav" id="pills-tab" role="tablist">
                  {% for cat in category %}
                  <li class="nav-item">
                    <a class="nav-link " id="{{cat}}-tab" data-toggle="pill" href="#pills-{{cat}}" role="tab" aria-controls="pills-{{cat}}" aria-selected="true">{{cat}}</a>
                  </li>
                  {% endfor %}
                  
                </ul>
                <div class="tab-content" id="pills-tabContent">
                  {% for cat in category %}
                    <div class="tab-pane fade show" id="pills-{{cat}}" role="tabpanel" aria-labelledby="pills-{{cat}}-tab">
                    {% for meal in meal_list %}
                      {% if meal.category == cat %}
                          <div class="d-block d-md-flex menu-food-item">
                            <div class="text order-1 mb-3">
                              <h3><a href="{% url 'meals:meal_detail' meal.slug%}">{{meal}}</a></h3>
                              <p>{{meal.description}}</p>
                            </div>
                            <div class="price order-2">
                              <strong>${{meal.price}}</strong>
                            </div>
                          </div> <!-- .menu-food-item -->
                          {% endif%}
                    {%endfor%}
                  </div>

                  {%endfor%}
                  

                  <div class="tab-pane fade" id="pills-lunch" role="tabpanel" aria-labelledby="pills-lunch-tab">
                    
                    <div class="d-block d-md-flex menu-food-item">
                      <div class="text order-1 mb-3">
                        <h3><a href="#">Jumbo Lump Crab Stack</a></h3>
                        <p>Spinach and artichokes in a creamy cheese dip with warm tortilla chips &amp; salsa.</p>
                      </div>
                      <div class="price order-2">
                        <strong>$12.49</strong>
                      </div>
                    </div> <!-- .menu-food-item -->

                    <div class="d-block d-md-flex menu-food-item">
                      <div class="text order-1 mb-3">
                        <h3><a href="#">Jamaican Chicken Wings</a></h3>
                        <p>Crisp tortilla and plantain chips covered with lightly spiced ground beef, melted cheese, pickled jalapeños, guacamole, sour cream and salsa.</p>
                      </div>
                      <div class="price order-2">
                        <strong>$15.99</strong>
                      </div>
                    </div> <!-- .menu-food-item -->

                    <div class="d-block d-md-flex menu-food-item">
                      <div class="text order-1 mb-3">
                        <h3><a href="#">Bahamian Seafood Chowder</a></h3>
                        <p>A heaping mountain of rings, handmade with Panko breading and shredded coconut flakes.</p>
                      </div>
                      <div class="price order-2">
                        <strong>$10.99</strong>
                      </div>
                    </div> <!-- .menu-food-item -->

                    <div class="d-block d-md-flex menu-food-item">
                      <div class="text order-1 mb-3">
                        <h3><a href="#">Grilled Chicken &amp; Tropical Fruit on Mixed Greens</a></h3>
                        <p>Lobster and tender shrimp, with onions, sweet peppers, spinach and our three cheese blend. Griddled and served with tomato salsa and sour cream.</p>
                      </div>
                      <div class="price order-2">
                        <strong>$12.99</strong>
                      </div>
                    </div> <!-- .menu-food-item -->

                  </div>
                  <div class="tab-pane fade" id="pills-dinner" role="tabpanel" aria-labelledby="pills-dinner-tab">
                    
                    <div class="d-block d-md-flex menu-food-item">
                      <div class="text order-1 mb-3">
                        <h3><a href="#">Grilled Top Sirlion Steak</a></h3>
                        <p>Spinach and artichokes in a creamy cheese dip with warm tortilla chips &amp; salsa.</p>
                      </div>
                      <div class="price order-2">
                        <strong>$18.99</strong>
                      </div>
                    </div> <!-- .menu-food-item -->

                    <div class="d-block d-md-flex menu-food-item">
                      <div class="text order-1 mb-3">
                        <h3><a href="#">Steak Oscar</a></h3>
                        <p>Crisp tortilla and plantain chips covered with lightly spiced ground beef, melted cheese, pickled jalapeños, guacamole, sour cream and salsa.</p>
                      </div>
                      <div class="price order-2">
                        <strong>$23.99</strong>
                      </div>
                    </div> <!-- .menu-food-item -->

                    <div class="d-block d-md-flex menu-food-item">
                      <div class="text order-1 mb-3">
                        <h3><a href="#">Skirt Steak Churrasco</a></h3>
                        <p>A heaping mountain of rings, handmade with Panko breading and shredded coconut flakes.</p>
                      </div>
                      <div class="price order-2">
                        <strong>$20.99</strong>
                      </div>
                    </div> <!-- .menu-food-item -->

                    <div class="d-block d-md-flex menu-food-item">
                      <div class="text order-1 mb-3">
                        <h3><a href="#">Grilled Beef Steak</a></h3>
                        <p>Lobster and tender shrimp, with onions, sweet peppers, spinach and our three cheese blend. Griddled and served with tomato salsa and sour cream.</p>
                      </div>
                      <div class="price order-2">
                        <strong>$20.99</strong>
                      </div>
                    </div> <!-- .menu-food-item -->

                  </div>
                </div>


              </div>
            </div>
          </div>
        </div>


        

      </div> <!-- .main-wrap -->
      

{%endblock %}

meals/templates/Meals/meal_list.html
<h1>Meals list</h1>
{% for meal in meal_list%}
	<h2><a href="{% url 'meals:meal_detail' meal.slug %}">{{meal}}</a></h2>
	{{meal.price}}$
{%endfor%}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <title>Colorlib Diner</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:300,400,700,800|Open+Sans:300,400,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static  'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">

    <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    

    <div class="site-wrap">
      
      <nav class="site-menu">
        <div class="site-menu-inner">
          <ul class="list-unstyled">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="{% url 'blog:about_us' %}">About Us</a></li>
            <li><a href="/meals/">Our Menu</a></li>
            <li><a href="{% url 'blog:post_list'%}">Our Blog</a></li>
            <li><a href="{% url 'reservation:reservation'%}">Reserve A Table</a></li>
            <li><a href="/contact/">Contact</a></li>
          </ul>
        </div>
      </nav>

      <header class="site-header">
        <div class="row align-items-center">
          <div class="col-5 col-md-3">
             <ul class="list-unstyled social">
              <li><a href="#"><span class="fa fa-facebook"></span></a></li>
              <li><a href="#"><span class="fa fa-twitter"></span></a></li>
              <li><a href="#"><span class="fa fa-instagram"></span></a></li>
            </ul>
          </div>
          <div class="col-2 col-md-6 text-center">
            <a href="/" class="site-logo">D</a>
          </div>
          <div class="col-5 col-md-3 text-right menu-burger-wrap">
            <a href="#" class="site-nav-toggle js-site-nav-toggle"><i></i></a>

          </div>
        </div>
       
      </header> <!-- site-header -->
      
  {% block content%}
  {%endblock%}
      

      <footer>
        <div class="site-footer">
          <div class="container">
            <div class="row small-gutters mb-5">
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="100">
                <div class="footer-widget">
                  <h3>Diner Restaurant</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel neque, odio illum. Est minima sint minus sunt ducimus.</p>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="200">
                <div class="footer-widget">
                  <h3>Lunch Service</h3>
                  <p>Booking from 12:00pm - 1:30pm</p>
                  <h3>Dinner Service</h3>
                  <p>Everyday: <br> Booking from 6:00pm - 9:00pm</p>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="300">
                <div class="footer-widget">
                  <h3>Quick Links</h3>
                  <ul>
                    <li><a href="#">Help &amp; Support</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Get in Touch</a></li>
                    <li><a href="#">Testimonials</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="400">
                <div class="footer-widget footer-contact-widget">

                  <h3>Subscribe</h3>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                  <form action="" class="form-subscribe mb-5">
                    <div class="form-group form-field">
                      <input type="submit" value="Send" class="btn btn-primary">
                      <input type="text" class="form-control" placeholder="Email">
                    </div>
                  </form>

                  <h3>Contact Us</h3>
                  <p class="contact-email">info@yourdomain.com</p>
                  <p class="contact-phone">1-444-123-9829</p>
                  
                  
                </div>
              </div>
            </div>
          </div>
          
        </div>
      </footer>

      <div class="site-footer-copyright">
        <div class="container">
          <div class="row">

             <p class="footer-text col-md-12"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>

    </div>

    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>

    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>

    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>

    <script src="{% static 'js/aos.js' %}"></script>
    

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>

    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>